# Generated by Django 4.2.4 on 2023-11-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemodel',
            name='size',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
