# Generated by Django 4.2.4 on 2023-11-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoemodel',
            old_name='size',
            new_name='sizes',
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
