# Generated by Django 4.2.4 on 2023-10-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sizes',
            table='main_size',
        ),
    ]
