# Generated by Django 4.2.4 on 2023-10-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_address_state_remove_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemodel',
            name='size',
            field=models.CharField(default='', max_length=16),
        ),
    ]
