# Generated by Django 4.2.4 on 2023-11-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_size_shoemodel_sizes_alter_shoemodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
