# Generated by Django 4.2.4 on 2023-12-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_shoesize_size_shoesize_euro_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoeimage',
            old_name='extra_images',
            new_name='image',
        ),
    ]
