# Generated by Django 4.2.4 on 2023-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shoemodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemodel',
            name='size',
            field=models.CharField(default='SomeDefaultValue', max_length=16),
        ),
    ]
