# Generated by Django 4.2.4 on 2023-12-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_extra_images_shoeimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoeImage',
            new_name='ShoeGalleryImages',
        ),
    ]
