# Generated by Django 4.2.4 on 2023-12-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_shoeimage_shoegalleryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoegalleryimages',
            name='shoe_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_gallery', to='main.shoemodel'),
        ),
    ]
