# Generated by Django 4.2.4 on 2023-12-12 19:10

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cartitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_images', models.ImageField(upload_to=main.models.shoe_image_directory_path)),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.shoemodel')),
            ],
        ),
    ]
