# Generated by Django 4.2.4 on 2023-12-13 08:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shoeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.JSONField(default=main.models.default_size)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoemodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoemodel',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='ShoeColor',
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='sizes',
            field=models.ManyToManyField(default=main.models.default_size, to='main.shoesize'),
        ),
    ]
