# Generated by Django 4.2.4 on 2023-10-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
