# Generated by Django 4.2.4 on 2023-12-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shoesize_remove_shoemodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemodel',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='main.shoesize'),
        ),
        migrations.AlterField(
            model_name='shoesize',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
