# Generated by Django 5.0 on 2024-01-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_shoesize_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_category', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shoegalleryimages',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='shoegalleryimages',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='category',
            field=models.ForeignKey(blank=True, default='', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categorymodel'),
        ),
    ]
