# Generated by Django 5.0.1 on 2024-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_categorymodel_level_categorymodel_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemodel',
            name='name',
            field=models.CharField(default='temp_name', editable=False, max_length=45),
        ),
    ]
