# Generated by Django 5.0.1 on 2024-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_shoemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoemodel',
            name='model',
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
