# Generated by Django 5.0.1 on 2024-01-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_shoemodel_model_alter_shoemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='m_category',
            new_name='name',
        ),
    ]
