# Generated by Django 5.0.1 on 2024-01-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_m_category_categorymodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoebrand',
            options={'ordering': ('tree_id', 'level')},
        ),
        migrations.AlterModelTable(
            name='shoebrand',
            table='brand',
        ),
    ]
