# Generated by Django 5.0.1 on 2024-01-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_shoebrand_options_alter_shoebrand_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoemodel',
            name='parent',
        ),
    ]
