# Generated by Django 5.0.1 on 2024-01-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_shoemodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='parent',
            field=models.ForeignKey(blank=True, default='', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.categorymodel', verbose_name='category'),
        ),
    ]
