# Generated by Django 5.0 on 2024-01-11 14:56

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_shoemodel_category_shoemodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shoebrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='shoebrand',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.shoebrand'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='parent',
            field=models.ForeignKey(blank=True, default='', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_models', to='main.categorymodel'),
        ),
    ]
