# Generated by Django 5.0 on 2024-01-16 18:59

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_categorymodel_parent_alter_shoebrand_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.shoebrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='shoegalleryimages',
            name='image',
            field=models.ImageField(upload_to=main.models.shoe_image_directory_path, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='brand',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.shoebrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='desc',
            field=models.TextField(verbose_name='Описание к модели'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='image',
            field=models.ImageField(default='', upload_to='gallery', verbose_name='Изображение миниатюры'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Имя модели'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='parent',
            field=models.ForeignKey(blank=True, default='', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_models', to='main.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='shoemodel',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='main.shoesize', verbose_name='Размеры'),
        ),
    ]
